### ISSUE TITLE
JetBrains Exception when attemping to refactor/rename a file

### ISSUE THREAD

**Issue by codewriter3000** [clojure-lsp/clojure-lsp-intellij#32]
**Describe the bug**
I get an exception leading me to this tool every time I attempt to rename a file.

**To Reproduce**
1. Click on a file.
2. Either hit Shift + F6 (the shortcut for refactoring), or right-click on it to bring up the tooltip to rename it.

**Expected behavior**
A dialog for the new file name.

<details>
 <summary><b>Log - client <-> server</b></summary>
<pre>
n/a
</pre>
</details>

<details>
 <summary><b>Log - clojure-lsp</b></summary>
<pre>
java.lang.StackOverflowError
	at com.intellij.openapi.util.registry.Registry.getInstance(Registry.java:180)
	at com.intellij.openapi.util.registry.Registry.get(Registry.java:45)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:58)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.reportValueProvidedByRulesUsage(PreCachedDataContext.java:250)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getDataInner(PreCachedDataContext.java:221)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext$InjectedDataContext.lambda$getDataInner$0(PreCachedDataContext.java:387)
	at com.intellij.openapi.actionSystem.InjectedDataKeys.getInjectedData(InjectedDataKeys.java:57)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext$InjectedDataContext.getDataInner(PreCachedDataContext.java:387)
	at com.intellij.openapi.actionSystem.impl.PreCachedDataContext.getData(PreCachedDataContext.java:174)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:57)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invoke(rename.clj:45)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invoke(rename.clj:45)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invoke(rename.clj:45)
	at com.github.clojure_lsp.intellij.extension.rename$_invoke.invokeStatic(rename.clj:48)
...
(this goes on for a pretty long time)
</pre>
</details>

**User details (please complete the following information):**
 - OS: Windows 11
 - Editor: PyCharm 2023.3
 - Version: 1.14.9

**Comment by ericdallo** [comment]
@codewriter3000, I can't repro the problem and I'm almost sure it's not related with the plugin itself but the available heap memory available for PyCharm, can you try to increase it following https://www.jetbrains.com/help/pycharm/increasing-memory-heap.html?

**Comment by codewriter3000** [comment]
I just changed it to 8192 and I still get the same StackOverflowException.

Also I don't have this issue when I disable the Clojure LSP plugin.
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/58712923/f92b3ba9-c554-4c34-8fc6-05bdd517fe43)

**Comment by codewriter3000** [comment]
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/58712923/8dd70849-4b9b-45a5-9e7d-219d5c0e501c)
I still have this problem with version 2.1.0.

**Comment by ericdallo** [comment]
@codewriter3000 does that happens on https://github.com/ericdallo/clojure-sample?

**Comment by ericdallo** [comment]
@codewriter3000 should be fixed on 2.3.0
